"""
Playwright Research Data Extractor
-----------------------------------
This script:
  ✔ Visits a list of websites
  ✔ Extracts visible text, headings, metadata
  ✔ Cleans + formats the content
  ✔ Saves everything into a single output text file

Author: Mohamed Uvais (Assignment - Playwright Module)
"""

from playwright.sync_api import sync_playwright
import time
import re

# ---------------------------------------------------------
# 1️⃣ List of all websites from your screenshot
# ---------------------------------------------------------
TARGET_URLS = [
    # Week 1
    "https://code.visualstudio.com/download",
    "https://www.python.org/downloads/release/python-3110/",
    "https://pyautogui.readthedocs.io/en/latest/",
    "https://huggingface.co/",
    "https://huggingface.co/spaces",
    "https://github.com/",
    "https://colab.research.google.com/",
    "https://www.cursor.com/",

    # Week 2
    "https://www.selenium.dev/documentation/",
    "https://playwright.dev/docs/intro",
    "https://restfulapi.net/",
    "https://flask.palletsprojects.com/en/stable/",
    "https://docs.streamlit.io/"
]

# ---------------------------------------------------------
# 2️⃣ Clean extracted text (remove unnecessary characters)
# ---------------------------------------------------------
def clean_text(text: str) -> str:
    text = re.sub(r"\s+", " ", text)         # Remove extra spaces/newlines
    text = re.sub(r"<.*?>", "", text)        # Remove HTML tags
    return text.strip()

# ---------------------------------------------------------
# 3️⃣ Extract metadata + headings + visible text
# ---------------------------------------------------------
def extract_page_info(page):
    title = page.title()

    headings = page.locator("h1, h2, h3").all_text_contents()
    headings = [clean_text(h) for h in headings]

    full_text = clean_text(page.inner_text("body"))

    return title, headings, full_text

# ---------------------------------------------------------
# 4️⃣ MAIN FUNCTION – visit each site & export data
# ---------------------------------------------------------
def extract_all_sites():
    output_file = "playwright_research_output.txt"
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("📘 PLAYWRIGHT RESEARCH EXPORT\n")
        f.write("Generated by Playwright automation\n\n")
        f.write("="*80 + "\n\n")

    with sync_playwright() as pw:
        browser = pw.chromium.launch(headless=True)
        context = browser.new_context()

        for url in TARGET_URLS:
            page = context.new_page()

            print(f"🔍 Visiting: {url}")
            try:
                page.goto(url, timeout=60000)
                time.sleep(2)

                title, headings, body = extract_page_info(page)

                # Append output to file
                with open(output_file, "a", encoding="utf-8") as f:
                    f.write(f"🌐 URL: {url}\n")
                    f.write(f"📌 Title: {title}\n\n")
                    f.write("🔹 HEADINGS:\n")
                    for h in headings:
                        f.write(f"   - {h}\n")

                    f.write("\n🔹 FULL TEXT CONTENT:\n")
                    f.write(body[:5000])  # Limit output, can remove this limit
                    f.write("\n\n" + "-"*80 + "\n\n")

            except Exception as e:
                print(f"❌ Failed to extract {url}: {e}")

        browser.close()

    print("\n✅ Extraction complete! File saved as:")
    print("👉 playwright_research_output.txt")

# ---------------------------------------------------------
# 5️⃣ Run the extractor
# ---------------------------------------------------------
if __name__ == "__main__":
    extract_all_sites()